### ISSUE TITLE
Integrate CRC-24 from OpenPGP

### ISSUE THREAD

**Issue by cfcs** [mirage/checkseum#17]
Hey, this is more a question than an issue, but I wanted to ask if you would accept a PR to integrate CRC-24 (which is used in OpenPGP)?

The code is already written, but I wanted to ask before submitting a PR.
I'd be happy to refactor it to not use [`Cs`](https://github.com/cfcs/ocaml-cs), and to have a streaming interface.

- [C reference implementation](https://tools.ietf.org/html/rfc4880#section-6.1)
- [slightly hacky pure OCaml port](https://github.com/cfcs/ocaml-openpgp/blob/master/lib/types.ml#L832-L878)

**Comment by cfcs** [comment]
ping @dinosaure

**Comment by dinosaure** [comment]
I'm ok with it but you just miss the release :p !

**Comment by dinosaure** [comment]
See #43
