### ISSUE TITLE
Use virtual libraries

### ISSUE THREAD

**Issue by emillon** [mirage/checkseum#22]
Hi,

The custom link technique used in `checkseum` makes it impossible to use in certain contexts. For example, any library that depends on `checkseum` cannot be used with `ppx_expect`. Now that there is support in dune for this use case, can `checkseum` use virtual libraries?

Thanks

**Comment by TheLortex** [comment]
I've made the modifications. This breaks compatibility with the current Mirage build system.
Moreover a second PR will be needed when the variant feature will be merged (hopefully in dune 1.9).
