### ISSUE TITLE
xen_linksopt is used when we want to link with checkseum.ocaml

### ISSUE THREAD

**Issue by dinosaure** [mirage/checkseum#23]
/cc @cfcs, not so easy to fix it when `META` file template can not be destructed to put inside `xen` sub-package the tricky line.

**Comment by cfcs** [comment]
:-/

**Comment by dinosaure** [comment]
The bug still exists into Mirage 3 but should disappear with Mirage 4.

**Comment by dinosaure** [comment]
Currently, `checkseum.1.1.0-1` should fix the problem. If I understand correctly the problem:

> when we choose `checkseum.ocaml`, we statically link with `xen` C stubs library when we make an unikernel

The problem should appear on the `mirage` tool which chooses at the end static libraries needed by the unikernel. I suspect that `ocamlfind` gives to us _by default_ `xen` C stubs even if we choose `checkseum.ocaml`. It should be interesting to see if we can reproduce it - a solution should be done by the `META` file, I think.

**Comment by dinosaure** [comment]
Ok, I understand correctly what happens and the problem. Currently, the command to get static library according the target by `mirage` is:

```sh
$ ocamlfind query -format "%d\t%(freestanding_linkopts)" checkseum
```

`mirage` does this command because `checkseum` is one of dependencies of your _unikernel_. Even if, by side, you add the right `_tags` with `true: package(checkseum.ocaml)`, `mirage` still links your _unikernel_ with static C library.

To fix that, a possible idea is to put `xen_linkopts`/`freestanding_linkopts` into the sub-package of `checkseum.c` (into the `META` file). `mirage` will do the same command but only for `checkseum.c`. However, it's really tricky when:
- we are not able to produce our own `META` file with `dune` (due to variants)
- even if currently we put these lines by hands, the way to put into the right sub-package will be trickier

So, at least, no solution exist about your issue. Sorry! May be MirageOS 4 will fix that but I'm not totally aware about that.

**Comment by cfcs** [comment]
At the moment I have no problem compiling checkseum-based things for Xen. I'm not sure if something got fixed in the tooling, or if I am just using the non-broken (old) version of `checkseum`. I'll investigate and report back.

**Comment by dinosaure** [comment]
`xen_linkopts` is deleted - however, that does not mean that the bug disappear. Again, due to a non-control of the `META` file, it's hard to place `*_linkopts` in the right sub-package. But, as far as I can tell, this error will disappear for MirageOS 4. So, I believe I can close this issue.
