### ISSUE TITLE
In "src-c/native/", 'STDC' is never ever defined

### ISSUE THREAD

**Issue by pirbo** [mirage/checkseum#30]
`STDC'` is defined in "zconf.h" (of zlib) that is not included in `src-c/native/` therefore some code is very probably dead (and does not compile on my machine)

As an experiment, I replaced `STDC` by the more common `__STDC__` (but actually the cases of "definition" in zlib are more complex of course) and I had to apply the extra
```
diff --git a/src-c/native/crc32.c b/src-c/native/crc32.c
index 53f01f5..a62d26c 100644
--- a/src-c/native/crc32.c
+++ b/src-c/native/crc32.c
@@ -532,7 +532,7 @@ static unsigned long crc32_big(unsigned long crc, const unsigned char * buf, siz
     len--;
   }
 
-  buf4 = (const crc_t *)(cost void *)buf; /* Obj.magic */
+  buf4 = (const crc_t *)(const void *)buf; /* Obj.magic */
 
   while (len >= 32) {
     DOBIG32;
```
to make it compile.

(I discovered that by trying to cross compile checkseum for windows in the context of ocaml-cross/opam-cross-windows where "src-c/native/size_t.h" is a burden because `WIN32` is defined but `BaseTsd.h` does not exists as we are using a (cross compiler) gcc)

**Comment by pirbo** [comment]
I see the change in 0.1.1 but isn't it exactly
```
# include <stddef.h>
```
that would define `_STDDEF_H` such that

**Comment by dinosaure** [comment]
I completely forgot your issue, really sorry. I updated to STDDEF_H to be able to compile with OCaml 4.08.0+32bit bit it seems not a good solution. I will try to fix that this week.

**Comment by dinosaure** [comment]
So (yes, it's a long week ... sorry) I integrated your patch and unlock the dead code. Could you test my PR?

**Comment by pirbo** [comment]
So the answer is "no, with your patch, I still can't cross compile because 
> in "src-c/native/size_t.h", WIN32 is defined but BaseTsd.h does not exists as I am using a (cross compiler) gcc
I'll try to look deeper as soon as I have a moment..."

**Comment by dinosaure** [comment]
Close by #45
