### ISSUE TITLE
checkseum 0.1.1 no longer uses variants

### ISSUE THREAD

**Issue by hannesm** [mirage/checkseum#35]
i think the commit https://github.com/mirage/checkseum/commit/04efbed60f63e8107937d5b9357f7e92b57ae2c1 somehow slipped into master... in opam, there's a conflict with mirage-runtime <4.0.0.

**Comment by dinosaure** [comment]
Yes, it's weird :/ , I will fix this tonight and redo the release.

**Comment by dinosaure** [comment]
Fixed by https://github.com/mirage/checkseum/commit/8e90d0c9de162a055ec0de9cd610c9b80aafe2e2.
